Add Wip

diff --git a/.github/workflows/sdlc-pipeline.yml b/.github/workflows/sdlc-pipeline.yml
--- a/.github/workflows/sdlc-pipeline.yml
+++ b/.github/workflows/sdlc-pipeline.yml
@@ -78,11 +78,20 @@ jobs:
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: results/codeql.sarif
+          category: code-scanning
+
+      - name: Validar existencia de ShellCheck SARIF
+        run: |
+          if [ ! -f results/shellcheck.sarif ]; then
+            echo "Error: Archivo shellcheck.sarif no encontrado."
+            exit 1
+          fi
 
       - name: Subir SARIF de ShellCheck
         uses: github/codeql-action/upload-sarif@v3
         with:
-          sarif_file: shellcheck.sarif
+          sarif_file: results/shellcheck.sarif
+          category: code-scanning
 
   dast:
     runs-on: ubuntu-latest
@@ -109,6 +118,7 @@ jobs:
       run: echo "Stakeholders test and approve features."
 
   deploy-production:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     needs: uat
     if: github.ref == 'refs/heads/main'
